spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chinashop
    username: Freusturz
    password: belkacheat0301
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true